name: SmartTrim
options:
  bundleIdPrefix: com.smarttrim
  deploymentTarget:
    macOS: "14.0"

settings:
  SWIFT_VERSION: "6.0"

targets:
  SmartTrim:
    type: application
    platform: macOS
    sources: [SmartTrim]
    settings:
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_STRICT_CONCURRENCY: complete
      LSApplicationCategoryType: public.app-category.utilities
      INFOPLIST_KEY_LSUIElement: YES
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      ENABLE_HARDENED_RUNTIME: YES
      MARKETING_VERSION: "1.0.1"
      CURRENT_PROJECT_VERSION: "2"

  SmartTrimTests:
    type: bundle.unit-test
    platform: macOS
    sources: [SmartTrimTests]
    dependencies:
      - target: SmartTrim
    settings:
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_STRICT_CONCURRENCY: complete
